# Generated by Django 2.2 on 2020-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk_coffe', models.CharField(max_length=50)),
                ('type_coffe', models.CharField(max_length=50)),
                ('roasteds', models.CharField(max_length=20)),
                ('process', models.CharField(max_length=50)),
                ('altitudes', models.CharField(max_length=50)),
            ],
        ),
    ]
