# Generated by Django 2.2 on 2020-08-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(default='Lola'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
