# Generated by Django 2.2 on 2020-09-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
