# Generated by Django 2.2 on 2020-09-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0003_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Game',
        ),
    ]
